import { Suspense } from 'react'
import { Button } from '@/components/ui/button'
import { getCachedValue } from './data'
import { incrementAction } from './actions'

async function CachedValue() {
  const { value, computedAt } = await getCachedValue()
  return (
    <div className="rounded-lg border p-4 text-sm">
      <p>
        Cached value: <span className="font-mono font-semibold">{value}</span>
      </p>
      <p className="text-muted-foreground">
        Computed at <span className="font-mono">{computedAt}</span>
      </p>
    </div>
  )
}

/**
 * Cache Components demo. The `PageProps<'/demo/cache'>` helper (generated by
 * `next typegen`) types the Next.js 16 async route props. `params` /
 * `searchParams` are Promises here — `await` them inside a `<Suspense>`
 * boundary (they're uncached Request data), never at the static top level.
 */
export default async function CacheDemoPage(_props: PageProps<'/demo/cache'>) {
  return (
    <main className="min-h-screen bg-background">
      <div className="container mx-auto max-w-xl px-8 py-16 space-y-6">
        <h1 className="text-2xl font-semibold">Cache Components demo</h1>
        <p className="text-sm text-muted-foreground">
          The value below is produced by a <code>use cache</code> function
          tagged <code>demo-data</code> with the <code>minutes</code> profile.
          Incrementing calls <code>updateTag</code> for read-your-writes.
        </p>

        {/* Cached dynamic content is read inside <Suspense> per Cache Components. */}
        <Suspense fallback={<p className="text-sm">Loading…</p>}>
          <CachedValue />
        </Suspense>

        <form action={incrementAction}>
          <Button type="submit">Increment &amp; updateTag</Button>
        </form>
      </div>
    </main>
  )
}
